import { MB } from "../units.js";

export const ENDPOINT_SHARE_THRESHOLD = 0.05;

export const DISTRIBUTION_DOMINANCE_THRESHOLD = 0.5;
export const CONCENTRATION_SHARE_THRESHOLD = 0.75;
export const NARRATIVE_CONCENTRATION_SHARE = 0.5;
export const SPIKE_SHARE_THRESHOLD = 0.7;
export const STUDIO_NEGLIGIBLE_SHARE_THRESHOLD = 0.2;

export const CRITICAL_BYTES_THRESHOLD = 100 * MB;
export const CRITICAL_REQUESTS_THRESHOLD = 1_000;
export const CRITICAL_SHARE_THRESHOLD = 0.25;
export const CRITICAL_TOTAL_BYTES_THRESHOLD = 10 * MB;
export const CRITICAL_TOTAL_REQUESTS_THRESHOLD = 100;

export const REASSURING_5XX_RATE = 0.001;
